In [2]:
import pypsa
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
n = pypsa.Network('/home/raj08555/dev/sandbox-cs/pypsa-earth-sec/results/MT_opt30_cres_csec/postnetworks/elec_s_30_ec_lc1.0_Co2L_168H_2030_0.076_NZ_200export.nc')
n_pre = pypsa.Network('/home/raj08555/dev/sandbox-cs/pypsa-earth-sec/results/MT_opt30_nores_csec/postnetworks/elec_s_30_ec_lc1.0_Co2L_168H_2030_0.076_NZ_200export.nc')

INFO:pypsa.io:Imported network elec_s_30_ec_lc1.0_Co2L_168H_2030_0.076_NZ_200export.nc has buses, carriers, generators, global_constraints, lines, links, loads, stores
INFO:pypsa.io:Imported network elec_s_30_ec_lc1.0_Co2L_168H_2030_0.076_NZ_200export.nc has buses, carriers, generators, global_constraints, lines, links, loads, stores

## Check for overwritten values

In [3]:
n_pre.generators.loc[n_pre.generators.carrier == 'solar'].p_nom_max.head()

Generator
NAM10_AC solar    124690.082525
NAM11_AC solar    156748.971625
NAM12_AC solar     48700.299344
NAM14_AC solar      1354.481505
NAM15_AC solar     14500.184244
Name: p_nom_max, dtype: float64

In [4]:
n.generators.loc[n.generators.carrier == 'solar'].p_nom_max.head()

Generator
NAM10_AC solar    110917.0000
NAM11_AC solar    168621.0000
NAM12_AC solar    225533.7525
NAM13_AC solar      5225.7700
NAM14_AC solar     88613.9000
Name: p_nom_max, dtype: float64

In [5]:
n.generators.loc[n.generators.carrier == 'solar'].p_nom_max - n_pre.generators.loc[n_pre.generators.carrier == 'solar'].p_nom_max

Generator
NAM10_AC solar    -13773.082525
NAM11_AC solar     11872.028375
NAM12_AC solar    176833.453156
NAM13_AC solar              NaN
NAM14_AC solar     87259.418495
NAM15_AC solar    102868.815756
NAM16_AC solar      -256.669907
NAM17_AC solar    -21414.988440
NAM18_AC solar       205.533838
NAM19_AC solar      7977.151593
NAM1_AC solar      55103.853624
NAM20_AC solar       -91.896392
NAM22_AC solar    -72518.156614
NAM23_AC solar    -11954.558898
NAM24_AC solar    -24324.935305
NAM25_AC solar     88474.246019
NAM26_AC solar     85569.949196
NAM27_AC solar    -47107.942160
NAM28_AC solar     -2316.735477
NAM29_AC solar    -60687.746717
NAM2_AC solar      10637.990234
NAM30_AC solar     -1599.044887
NAM3_AC solar     -57054.861459
NAM4_AC solar      20312.449137
NAM5_AC solar       -722.526703
NAM6_AC solar     -17656.317780
NAM7_AC solar      36941.656521
NAM8_AC solar      11345.208341
NAM9_AC solar     -58942.705451
Name: p_nom_max, dtype: float64

## Check creation of new technology rooftop-solar

In [6]:
n.generators.loc[n.generators.carrier == 'rooftop-solar'].p_nom_max.head()

Generator
NAM10_AC rooftop-solar     0.0000
NAM11_AC rooftop-solar     0.0000
NAM12_AC rooftop-solar     0.0000
NAM13_AC rooftop-solar     0.0000
NAM14_AC rooftop-solar    90.9869
Name: p_nom_max, dtype: float64

## Comparison with raw Enertile data

In [7]:
raw_data_s = pd.read_csv('/home/raj08555/dev/sandbox0405/data_preprocessing/data/enertile/2030_Low/SOPV/respotentials315.csv')
raw_s_grouped = raw_data_s.groupby(['region']).sum().filter(like='NAM', axis=0)
raw_s_grouped.head()

,scenarioid,simyear,tech,step,annualcostEuroPMW,variablecostEuroPMWh,potstepsizeMW,flh,investmentEuroPKW,interestrate,lifetime,fixedomEuroPKW,installedcapacity
region,,,,,,,,,,,,,
NAM1,315,2030,sopv,0,52061.7,0,152952.00,1496.26,438.0,0.076,20,8.77000,0
NAM10,315,2030,sopv,0,52061.7,0,110917.00,1851.87,438.0,0.076,20,8.77003,0
NAM11,315,2030,sopv,0,52061.7,0,168621.00,1841.03,438.0,0.076,20,8.77001,0
NAM12,315,2030,sopv,0,52061.7,0,226099.00,1877.57,438.0,0.076,20,8.77000,0
NAM13,315,2030,sopv,0,52061.7,0,5225.77,1811.89,438.0,0.076,20,8.77000,0

In [8]:
raw_data_sr = pd.read_csv('/home/raj08555/dev/sandbox0405/data_preprocessing/data/enertile/2030_Low/PVR/respotentials189.csv')
raw_sr_grouped = raw_data_sr.groupby(['region']).sum().filter(like='NAM', axis=0)
raw_sr_grouped

,scenarioid,simyear,tech,step,annualcostEuroPMW,variablecostEuroPMWh,potstepsizeMW,flh,investmentEuroPKW,interestrate,lifetime,fixedomEuroPKW,installedcapacity
region,,,,,,,,,,,,,
NAM14,189,2030,pvr,0,106118,0,90.98690,1856.07,932,0.076,20,14,0
NAM19,189,2030,pvr,0,106118,0,13.23450,1821.81,932,0.076,20,14,0
NAM3,189,2030,pvr,0,106118,0,1.65431,1642.05,932,0.076,20,14,0
NAM30,189,2030,pvr,0,106118,0,39.70340,1713.55,932,0.076,20,14,0
NAM5,189,2030,pvr,0,106118,0,11.58010,1650.43,932,0.076,20,14,0
NAM6,189,2030,pvr,0,106118,0,135.65300,1549.07,932,0.076,20,14,0
NAM7,378,4060,pvrpvr,1,212236,0,368.91000,3241.70,1864,0.152,40,28,0
NAM9,189,2030,pvr,0,106118,0,2339.19000,1717.37,932,0.076,20,14,0

### Check consistency with respect to maximum installable capacity

In [9]:
n_solar = n.generators.loc[n.generators.carrier == 'solar'].p_nom_max
n_solar.index = n_solar.index.str.strip('_AC solar')

n_solar - raw_s_grouped.potstepsizeMW

NAM1       0.0000
NAM10      0.0000
NAM11      0.0000
NAM12   -565.2475
NAM13      0.0000
NAM14      0.0000
NAM15      0.0000
NAM16      0.0000
NAM17      0.0000
NAM18      0.0000
NAM19      0.0000
NAM2       0.0000
NAM20         NaN
NAM21         NaN
NAM22      0.0000
NAM23      0.0000
NAM24      0.0000
NAM25      0.0000
NAM26      0.0000
NAM27      0.0000
NAM28      0.0000
NAM29      0.0000
NAM3       0.0000
NAM30      0.0000
NAM4       0.0000
NAM5       0.0000
NAM6       0.0000
NAM7       0.0000
NAM8       0.0000
NAM9       0.0000
dtype: float64

In [10]:
n_solar_r = n.generators.loc[n.generators.carrier == 'rooftop-solar'].p_nom_max
n_solar_r.index = n_solar_r.index.str.strip('_AC rooftop-solar')

n_solar_r - raw_sr_grouped.potstepsizeMW

NAM1              NaN
NAM10             NaN
NAM11             NaN
NAM12             NaN
NAM13             NaN
NAM14    0.000000e+00
NAM15             NaN
NAM16             NaN
NAM17             NaN
NAM18             NaN
NAM19    0.000000e+00
NAM2              NaN
NAM20             NaN
NAM22             NaN
NAM23             NaN
NAM24             NaN
NAM25             NaN
NAM26             NaN
NAM27             NaN
NAM28             NaN
NAM29             NaN
NAM3     0.000000e+00
NAM30    0.000000e+00
NAM4              NaN
NAM5     0.000000e+00
NAM6     0.000000e+00
NAM7     5.684342e-14
NAM8              NaN
NAM9     0.000000e+00
dtype: float64

### Check consistency with respect to energy potential

In [11]:
n_solar_t = n.generators_t['p_max_pu'].filter(regex=' solar$')
n_solar_t = n_solar_t.sum()
n_solar_t.index = n_solar_t.index.str.strip('_AC solar')

n_solar_t * n_solar

Generator
NAM10    1.233860e+06
NAM11    1.863443e+06
NAM12    2.559202e+06
NAM13    5.736643e+04
NAM14    9.704784e+05
NAM15    1.286068e+06
NAM16    6.379897e+05
NAM17    1.799797e+05
NAM18    1.078265e+04
NAM19    9.229404e+04
NAM1     1.379141e+06
NAM20    0.000000e+00
NAM22    1.266943e+06
NAM23    1.518416e+05
NAM24    2.819511e+05
NAM25    1.028839e+06
NAM26    1.294516e+06
NAM27    6.204056e+05
NAM28    7.262742e+03
NAM29    1.198958e+06
NAM2     3.307056e+05
NAM30    1.828575e+03
NAM3     2.392215e+06
NAM4     6.370151e+05
NAM5     1.776076e+05
NAM6     7.679671e+05
NAM7     2.942361e+06
NAM8     2.163754e+05
NAM9     1.163340e+06
dtype: float64

In [12]:
#n_pre.links.loc[n_pre.links.carrier == "DAC"].p_nom_opt.sum()
n.links.loc[n.links.carrier == "DAC"].p_nom_opt.sum()

227.9006631409825

In [13]:
(n_pre.generators.loc[n_pre.generators.carrier == "solar"].p_nom_opt - n.generators.loc[n.generators.carrier == "solar"].p_nom_opt).sort_values().tail()

Generator
NAM29_AC solar     2566.025153
NAM15_AC solar     4662.233013
NAM24_AC solar     9205.331617
NAM16_AC solar    58470.529333
NAM13_AC solar             NaN
Name: p_nom_opt, dtype: float64

In [14]:
n.generators.loc[n.generators.carrier == "solar"].p_nom_max

Generator
NAM10_AC solar    110917.0000
NAM11_AC solar    168621.0000
NAM12_AC solar    225533.7525
NAM13_AC solar      5225.7700
NAM14_AC solar     88613.9000
NAM15_AC solar    117369.0000
NAM16_AC solar     58950.6000
NAM17_AC solar     17267.4000
NAM18_AC solar       992.2140
NAM19_AC solar      8370.6200
NAM1_AC solar     152952.0000
NAM20_AC solar         0.0000
NAM22_AC solar    119348.0000
NAM23_AC solar     14056.4000
NAM24_AC solar     26029.7000
NAM25_AC solar     95574.8000
NAM26_AC solar    125604.6000
NAM27_AC solar     61171.6000
NAM28_AC solar       682.6670
NAM29_AC solar    109876.0000
NAM2_AC solar      35049.8720
NAM30_AC solar       167.0720
NAM3_AC solar     245238.0000
NAM4_AC solar      62925.4000
NAM5_AC solar      17669.7000
NAM6_AC solar      81376.9400
NAM7_AC solar     305661.0000
NAM8_AC solar      24211.9000
NAM9_AC solar     109988.9000
Name: p_nom_max, dtype: float64

In [15]:
n_pre.generators.loc[n_pre.generators.carrier == "solar"].p_nom_max

Generator
NAM10_AC solar    124690.082525
NAM11_AC solar    156748.971625
NAM12_AC solar     48700.299344
NAM14_AC solar      1354.481505
NAM15_AC solar     14500.184244
NAM16_AC solar     59207.269907
NAM17_AC solar     38682.388440
NAM18_AC solar       786.680162
NAM19_AC solar       393.468407
NAM1_AC solar      97848.146376
NAM20_AC solar        91.896392
NAM22_AC solar    191866.156614
NAM23_AC solar     26010.958898
NAM24_AC solar     50354.635305
NAM25_AC solar      7100.553981
NAM26_AC solar     40034.650804
NAM27_AC solar    108279.542160
NAM28_AC solar      2999.402477
NAM29_AC solar    170563.746717
NAM2_AC solar      24411.881766
NAM30_AC solar      1766.116887
NAM3_AC solar     302292.861459
NAM4_AC solar      42612.950863
NAM5_AC solar      18392.226703
NAM6_AC solar      99033.257780
NAM7_AC solar     268719.343479
NAM8_AC solar      12866.691659
NAM9_AC solar     168931.605451
Name: p_nom_max, dtype: float64

In [16]:

n_pre.generators_t.p_max_pu.filter(regex=" solar$").sum().sort_values(ascending=False).head()*168

Generator
NAM12_AC solar    1782.271584
NAM24_AC solar    1749.204302
NAM10_AC solar    1748.290888
NAM28_AC solar    1737.939635
NAM19_AC solar    1734.387088
dtype: float64

In [17]:
n.generators_t.p_max_pu.filter(regex=" solar$").sum().sort_values(ascending=False).head()*168

Generator
NAM12_AC solar    1906.348622
NAM10_AC solar    1868.861963
NAM11_AC solar    1856.579872
NAM19_AC solar    1852.359621
NAM13_AC solar    1844.237362
dtype: float64

In [18]:
n.generators.loc[n.generators.carrier == "solar"].capital_cost
n_pre.generators.loc[n_pre.generators.carrier == "solar"].capital_cost

Generator
NAM10_AC solar    50855.958267
NAM11_AC solar    50855.958267
NAM12_AC solar    50855.958267
NAM14_AC solar    50855.958267
NAM15_AC solar    50855.958267
NAM16_AC solar    50855.958267
NAM17_AC solar    50855.958267
NAM18_AC solar    50855.958267
NAM19_AC solar    50855.958267
NAM1_AC solar     50855.958267
NAM20_AC solar    50855.958267
NAM22_AC solar    50855.958267
NAM23_AC solar    50855.958267
NAM24_AC solar    50855.958267
NAM25_AC solar    50855.958267
NAM26_AC solar    50855.958267
NAM27_AC solar    50855.958267
NAM28_AC solar    50855.958267
NAM29_AC solar    50855.958267
NAM2_AC solar     50855.958267
NAM30_AC solar    50855.958267
NAM3_AC solar     50855.958267
NAM4_AC solar     50855.958267
NAM5_AC solar     50855.958267
NAM6_AC solar     50855.958267
NAM7_AC solar     50855.958267
NAM8_AC solar     50855.958267
NAM9_AC solar     50855.958267
Name: capital_cost, dtype: float64

In [19]:
n.generators_t.p_max_pu.filter(regex=" solar$").sum()

Generator
NAM10_AC solar    11.124178
NAM11_AC solar    11.051071
NAM12_AC solar    11.347313
NAM13_AC solar    10.977603
NAM14_AC solar    10.951763
NAM15_AC solar    10.957472
NAM16_AC solar    10.822446
NAM17_AC solar    10.423093
NAM18_AC solar    10.867261
NAM19_AC solar    11.025950
NAM1_AC solar      9.016821
NAM20_AC solar     0.000000
NAM22_AC solar    10.615539
NAM23_AC solar    10.802308
NAM24_AC solar    10.831900
NAM25_AC solar    10.764752
NAM26_AC solar    10.306282
NAM27_AC solar    10.142053
NAM28_AC solar    10.638778
NAM29_AC solar    10.911922
NAM2_AC solar      9.435286
NAM30_AC solar    10.944831
NAM3_AC solar      9.754666
NAM4_AC solar     10.123338
NAM5_AC solar     10.051533
NAM6_AC solar      9.437158
NAM7_AC solar      9.626224
NAM8_AC solar      8.936738
NAM9_AC solar     10.576890
dtype: float64

In [20]:
n_pre.generators_t.p_max_pu.filter(like="solar").sum()
#n_pre.generators.loc[n_pre.generators.carrier == 'solar'].p_nom_max

Generator
NAM10_AC residential rural solar thermal collector               2.569533
NAM10_AC residential urban decentral solar thermal collector     2.569533
NAM10_AC services rural solar thermal collector                  2.569533
NAM10_AC services urban decentral solar thermal collector        2.569533
NAM10_AC solar                                                  10.406493
                                                                  ...
NAM9_AC residential urban decentral solar thermal collector      2.634624
NAM9_AC services rural solar thermal collector                   2.634624
NAM9_AC services urban decentral solar thermal collector         2.634624
NAM9_AC solar                                                   10.250148
NAM9_AC urban central solar thermal collector                    2.634624
Length: 173, dtype: float64

In [21]:
raw_data_s['potential'] = raw_data_s.flh * raw_data_s.potstepsizeMW
raw_data_s.groupby('region').sum()

,scenarioid,simyear,tech,step,annualcostEuroPMW,variablecostEuroPMWh,potstepsizeMW,flh,investmentEuroPKW,interestrate,lifetime,fixedomEuroPKW,installedcapacity,potential
region,,,,,,,,,,,,,,
NAM1,315,2030,sopv,0,52061.7,0,152952.000,1496.26,438.000,0.076,20,8.77000,0,2.288560e+08
NAM10,315,2030,sopv,0,52061.7,0,110917.000,1851.87,438.000,0.076,20,8.77003,0,2.054039e+08
NAM11,315,2030,sopv,0,52061.7,0,168621.000,1841.03,438.000,0.076,20,8.77001,0,3.104363e+08
NAM12,315,2030,sopv,0,52061.7,0,226099.000,1877.57,438.000,0.076,20,8.77000,0,4.245167e+08
NAM13,315,2030,sopv,0,52061.7,0,5225.770,1811.89,438.000,0.076,20,8.77000,0,9.468520e+06
NAM14,315,2030,sopv,0,52061.6,0,88613.900,1814.72,438.000,0.076,20,8.77000,0,1.608094e+08
NAM15,315,2030,sopv,0,52061.6,0,117369.000,1818.78,438.000,0.076,20,8.77001,0,2.134684e+08
NAM16,315,2030,sopv,0,52061.6,0,58950.600,1797.81,438.000,0.076,20,8.77000,0,1.059820e+08
NAM17,315,2030,sopv,0,52061.7,0,17267.400,1729.92,438.000,0.076,20,8.77000,0,2.987122e+07
NAM18,315,2030,sopv,0,52061.7,0,992.214,1797.28,438.000,0.076,20,8.77000,0,1.783286e+06
NAM19,315,2030,sopv,0,52061.7,0,8370.620,1826.82,438.000,0.076,20,8.77000,0,1.529162e+07
NAM2,630,4060,sopvsopv,1,104123.3,0,35049.872,3046.61,876.000,0.152,40,17.54000,0,5.470581e+07
NAM21,315,2030,sopv,0,52061.7,0,108142.000,1845.30,438.000,0.076,20,8.77002,0,1.995544e+08
NAM22,315,2030,sopv,0,52061.7,0,119348.000,1761.42,438.000,0.076,20,8.77001,0,2.102220e+08
NAM23,315,2030,sopv,0,52061.7,0,14056.400,1801.06,438.000,0.076,20,8.77000,0,2.531642e+07
NAM24,315,2030,sopv,0,52061.6,0,26029.700,1803.67,438.000,0.076,20,8.77000,0,4.694899e+07
NAM25,315,2030,sopv,0,52061.6,0,95574.800,1786.17,437.999,0.076,20,8.77001,0,1.707128e+08
NAM26,630,4060,sopvsopv,1,104123.1,0,125604.600,3390.30,876.000,0.152,40,17.54000,0,2.142937e+08
NAM27,315,2030,sopv,0,52061.6,0,61171.600,1680.44,438.000,0.076,20,8.77000,0,1.027952e+08
NAM28,315,2030,sopv,0,52061.7,0,682.667,1767.81,438.000,0.076,20,8.77000,0,1.206826e+06
NAM29,315,2030,sopv,0,52061.7,0,109876.000,1813.43,438.000,0.076,20,8.77002,0,1.992524e+08
NAM3,630,4060,sopvsopv,1,104123.6,0,245238.000,3229.67,876.000,0.152,40,17.54008,0,3.966187e+08
NAM30,315,2030,sopv,0,52061.7,0,167.072,1812.94,438.000,0.076,20,8.77000,0,3.028915e+05
NAM4,315,2030,sopv,0,52061.5,0,62925.400,1675.79,438.000,0.076,20,8.76998,0,1.054498e+08
NAM5,315,2030,sopv,0,52061.7,0,17669.700,1660.46,438.000,0.076,20,8.77000,0,2.933983e+07
NAM6,630,4060,sopvsopv,1,104123.3,0,81376.940,3087.17,876.000,0.152,40,17.54000,0,1.272412e+08
NAM7,630,4060,sopvsopv,1,104123.7,0,305661.000,3204.87,876.000,0.152,40,17.54004,0,4.881605e+08
NAM8,315,2030,sopv,0,52061.6,0,24211.900,1474.41,438.000,0.076,20,8.77000,0,3.569827e+07
NAM9,630,4060,sopvsopv,1,104123.3,0,109988.900,3445.21,876.000,0.152,40,17.54000,0,1.934400e+08

In [22]:
n_solar_r_t = n.generators_t['p_max_pu'].filter(regex=' rooftop-solar$')
n_solar_r_t = n_solar_r_t.sum()
n_solar_r_t.index = n_solar_r_t.index.str.strip('_AC rooftop-solar')

n_solar_r_t * n_solar_r

Generator
NAM10        0.000000
NAM11        0.000000
NAM12        0.000000
NAM13        0.000000
NAM14     1018.634854
NAM15        0.000000
NAM16        0.000000
NAM17        0.000000
NAM18        0.000000
NAM19      145.677799
NAM1         0.000000
NAM20        0.000000
NAM22        0.000000
NAM23        0.000000
NAM24        0.000000
NAM25        0.000000
NAM26        0.000000
NAM27        0.000000
NAM28        0.000000
NAM29        0.000000
NAM2         0.000000
NAM30      409.463234
NAM3        16.368161
NAM4         0.000000
NAM5       115.712036
NAM6      1265.533229
NAM7      3604.410261
NAM8         0.000000
NAM9     24178.169585
dtype: float64

In [23]:
raw_data_sr['potential'] = raw_data_sr.flh * raw_data_sr.potstepsizeMW
raw_data_sr.groupby('region').sum()

,scenarioid,simyear,tech,step,annualcostEuroPMW,variablecostEuroPMWh,potstepsizeMW,flh,investmentEuroPKW,interestrate,lifetime,fixedomEuroPKW,installedcapacity,potential
region,,,,,,,,,,,,,,
NAM14,189,2030,pvr,0,106118,0,90.98690,1856.07,932,0.076,20,14,0,1.688781e+05
NAM19,189,2030,pvr,0,106118,0,13.23450,1821.81,932,0.076,20,14,0,2.411074e+04
NAM3,189,2030,pvr,0,106118,0,1.65431,1642.05,932,0.076,20,14,0,2.716460e+03
NAM30,189,2030,pvr,0,106118,0,39.70340,1713.55,932,0.076,20,14,0,6.803376e+04
NAM5,189,2030,pvr,0,106118,0,11.58010,1650.43,932,0.076,20,14,0,1.911214e+04
NAM6,189,2030,pvr,0,106118,0,135.65300,1549.07,932,0.076,20,14,0,2.101360e+05
NAM7,378,4060,pvrpvr,1,212236,0,368.91000,3241.70,1864,0.152,40,28,0,5.987349e+05
NAM9,189,2030,pvr,0,106118,0,2339.19000,1717.37,932,0.076,20,14,0,4.017255e+06

In [24]:
n.objective/1e9
n_pre.objective/1e9

24.218679418142823

In [9]:
import numpy as np
def calc_all_gens(n):

    all_gens = ['biomass', 'coal', 'oil', 'OCGT', 'ror', 'nuclear', 'csp',

    'rooftop-solar', 'solar', 'onwind', 'onwind2', 'offwind',

    'offwind2', 'gas']

  #res_gens = list(n.carriers[n.carriers.co2_emissions == 0].index)

    res_gens_dict = {} 

    for gen_index in all_gens:

        res_index = n.generators[n.generators.carrier == gen_index].index

    # vars_conv_gens = n.generators_t.p[conv_index]
        n.generators.loc[n.generators.carrier == gen_index, "emissions"] = 0

        weightings = pd.DataFrame(

        np.outer(n.snapshot_weightings["generators"], [1.0] * len(res_index)),

        index=n.snapshots,

        columns=res_index,

        )
        res_gens_dict[gen_index] = round((weightings * n.generators_t.p[res_index]).sum().sum()/1e6)

    res_gens_dict["all"] = sum(res_gens_dict.values())
    return res_gens_dict

In [26]:
calc_all_gens(n)

{'biomass': 0,
 'coal': 0,
 'oil': 0,
 'OCGT': 0,
 'ror': 2,
 'nuclear': 0,
 'csp': 0,
 'rooftop-solar': 0,
 'solar': 325,
 'onwind': 0,
 'onwind2': 0,
 'offwind': 0,
 'offwind2': 0,
 'gas': 0,
 'all': 327}

In [27]:
calc_all_gens(n_pre)

{'biomass': 0,
 'coal': 0,
 'oil': 0,
 'OCGT': 0,
 'ror': 2,
 'nuclear': 0,
 'csp': 0,
 'rooftop-solar': 0,
 'solar': 235,
 'onwind': 49,
 'onwind2': 0,
 'offwind': 0,
 'offwind2': 0,
 'gas': 76,
 'all': 362}

In [28]:
n.loads_t.p.filter(regex="_AC$").sum()

Load
NAM10_AC       7.148077
NAM11_AC      46.366340
NAM12_AC      25.267992
NAM13_AC      13.500127
NAM14_AC      34.022460
NAM15_AC       5.628486
NAM16_AC      25.724836
NAM17_AC      12.728762
NAM18_AC      12.682824
NAM19_AC      12.953123
NAM1_AC      610.120998
NAM20_AC      14.878348
NAM22_AC      40.637454
NAM23_AC       6.610600
NAM24_AC       6.713634
NAM25_AC      20.687784
NAM26_AC      15.959872
NAM27_AC       7.264398
NAM28_AC      28.238051
NAM29_AC      92.122512
NAM2_AC      225.237021
NAM30_AC      59.628866
NAM3_AC      222.789647
NAM4_AC      514.804855
NAM5_AC      315.376769
NAM6_AC      561.210918
NAM7_AC     1122.250991
NAM8_AC       42.258583
NAM9_AC     1342.922846
dtype: float64

In [29]:
n.loads_t.p.filter(regex="_AC$").sum().sum()

5445.737174242563

In [30]:
n_pre.loads_t.p.filter(regex="_AC$").sum().sum()

5445.737174242563

In [31]:
n.links.loc[n.links.carrier =="OCGT"].p_nom_opt.sum()

0.027043741842176335

In [32]:
n_pre.links.loc[n_pre.links.carrier =="OCGT"].p_nom_opt.sum()

2879.3353230885027

In [6]:
def gen_emissions(n):
    conv_gens = list(n.carriers[n.carriers.co2_emissions > 0].index)
    conv_index = n.generators[n.generators.carrier.isin(conv_gens)].index
    # vars_conv_gens = n.generators_t.p[conv_index]

    n.generators.loc[n.generators.carrier.isin(conv_gens), "emissions"] = 0
    n.generators.loc[conv_index, "emissions"] = n.generators.loc[
        conv_index, "carrier"
    ].apply(lambda x: n.carriers.loc[x].co2_emissions)
    n.generators.emissions = n.generators.emissions.fillna(0)

    weightings = pd.DataFrame(
        np.outer(n.snapshot_weightings["generators"], [1.0] * len(conv_index)),
        index=n.snapshots,
        columns=conv_index,
    )

    emission_factors = pd.DataFrame(
        np.outer(
            [1.0] * len(n.snapshot_weightings["generators"]),
            n.generators.loc[conv_index, "emissions"],
        ),
        index=n.snapshots,
        columns=conv_index,
    )

    x=emission_factors*weightings
    x
    return (n.generators_t.p[conv_index] *x).sum().sum()/1e6

In [14]:
n5 = pypsa.Network("/home/raj08555/dev/sandbox-cs/pypsa-earth-sec/results/MT_opt30_bg/postnetworks/elec_s_30_ec_lc1.0_Co2L_144H_2030_0.082_AP_200export.nc")
#n0 = pypsa.Network("/home/raj08555/dev/sandbox-cs/pypsa-earth-sec/results/MT_con30/postnetworks/elec_s_30_ec_lc1.0_Co2L_3H_2030_0.082_AP_0export.nc")
nres = pypsa.Network("/home/raj08555/dev/sandbox-cs/pypsa-earth-sec/results/MT_opt30_2/postnetworks/elec_s_30_ec_lc1.0_Co2L_144H_2030_0.082_AP_200export.nc")
nres2=pypsa.Network("/home/raj08555/dev/sandbox-cs/pypsa-earth-sec/results/test_res/postnetworks/elec_s_30_ec_lc1.0_Co2L_144H_2030_0.082_AP_538export.nc")

INFO:pypsa.io:Imported network elec_s_30_ec_lc1.0_Co2L_144H_2030_0.082_AP_200export.nc has buses, carriers, generators, global_constraints, lines, links, loads, stores
INFO:pypsa.io:Imported network elec_s_30_ec_lc1.0_Co2L_144H_2030_0.082_AP_200export.nc has buses, carriers, generators, global_constraints, lines, links, loads, stores
INFO:pypsa.io:Imported network elec_s_30_ec_lc1.0_Co2L_144H_2030_0.082_AP_538export.nc has buses, carriers, generators, global_constraints, lines, links, loads, stores

In [35]:
print(n5.loads_t.p.filter(like="emission").sum().sum()*144/1e6, n0.loads_t.p.filter(like="emission").sum().sum()*144/1e6, nres.loads_t.p.filter(like="emission").sum().sum()*144/1e6)

-3.0501434918481447 -146.00686879010786 -3.0501434918481447

In [36]:
print(n5.stores_t.e.iloc[-1].filter(like="atmosphere", axis =0), n0.stores_t.e.iloc[-1].filter(like="atmosphere", axis =0), nres.stores_t.e.iloc[-1].filter(like="atmosphere", axis =0))

Store
co2 atmosphere   -176068.120512
Name: 2013-12-27 00:00:00, dtype: float64 Store
co2 atmosphere   -451658.61445
Name: 2013-12-31 21:00:00, dtype: float64 Store
co2 atmosphere   -477337.561453
Name: 2013-12-27 00:00:00, dtype: float64

In [10]:
print(gen_emissions(n5),gen_emissions(n0), gen_emissions(nres) )# (n.generators_t.p[conv_index] *x).sum().sum()/1e6

NameError: name 'n0' is not defined

In [38]:
print(calc_all_gens(n0) , "\n", calc_all_gens(nres))

{'biomass': 0, 'coal': 0, 'oil': 0, 'OCGT': 0, 'ror': 2, 'nuclear': 0, 'csp': 0, 'rooftop-solar': 0, 'solar': 22, 'onwind': 1, 'onwind2': 0, 'offwind': 0, 'offwind2': 0, 'gas': 0, 'all': 25}
 {'biomass': 0, 'coal': 0, 'oil': 0, 'OCGT': 0, 'ror': 2, 'nuclear': 0, 'csp': 0, 'rooftop-solar': 0, 'solar': 214, 'onwind': 49, 'onwind2': 0, 'offwind': 0, 'offwind2': 0, 'gas': 5, 'all': 270}

In [11]:
gen_emissions(n0) + n0.stores_t.e.filter(like="co2 atmosphere").iloc[-1]/1e6

NameError: name 'n0' is not defined

In [12]:
gen_emissions(nres) + nres.stores_t.e.filter(like="co2 atmosphere").iloc[-1]/1e6

Store
co2 atmosphere    0.61
Name: 2013-12-27 00:00:00, dtype: float64

In [15]:
gen_emissions(nres2) + nres2.stores_t.e.filter(like="co2 atmosphere").iloc[-1]/1e6

Store
co2 atmosphere   -0.451593
Name: 2013-12-27 00:00:00, dtype: float64